### ISSUE TITLE
Is this ready for use?

### ISSUE THREAD

**Issue by kmckinley** [spacialdb/fcm#1]
I'm currently using your GCM gem on a project and I'm upgrading my Android app to use FCM.  Is this gem ready for use?  Only asking because the initial push was 12 hours ago.

Thanks!

**Comment by kashif** [comment]
yes try it out... I think  for now the only difference between gcm and fcm is the api url. I think, and I have to confirm, the api key you need is from firebase.

Let me know if you have any questions... and thanks again!

**Comment by kmckinley** [comment]
Great.  I was also thinking the only difference was the url.  I'm implementing it right now, I'll let you know if I run into any trouble.

**Comment by FlintOFF** [comment]
When android app start i have registration_token, but not registration_id. Where i can find registration_id. Maybe you have method to get list of all devices?

**Comment by kashif** [comment]
@FlintOFF from reading the documentation the registration_tokens are the registration id, so you can use them from your ruby/rails server to send messages to a particular device

**Comment by FlintOFF** [comment]
@kashif thanks. Still not work. I tried send message from gem and have error 
`[{\"error\":\"MismatchSenderId\"}]`
And working well when I send message with same registration_id from https://console.firebase.google.com -> Notifications -> new message -> send to one device

**Comment by kashif** [comment]
thanks @FlintOFF for the bug report... looking at it now!

**Comment by FlintOFF** [comment]
Find bug. 
The size of registration_id was small, only 119 chars. This registration_id work on firebase console but not work over gem/CURL.
After build android app with minimal API 21 the size of registration_id is 152 chars, and this id work with firebase console and gem/CURL.

**Comment by kmckinley** [comment]
Has anyone successfully sent a push to an iOS device?  I'm able to send pushes to Android perfect, but no luck with iOS.  I'm able to send pushes from the Firebase console to both AdHoc and Dev builds though, so it makes me think it's something I'm doing wrong at the server.

Below is my basic setup for sending a push.  Anyone see anything wrong?

```ruby
    module Firebase
      class CloudMessaging
    
        def initialize()
          @api_key = ENV['FIREBASE_CLOUD_MESSAGING_API_KEY']
        end
    
    
        def send_notification(tokens, title, body, tag, sound, icon, color,
                              data_type, data_title, data_body, data_image_url, data_url)
          fcm = FCM.new(@api_key)
          options = {}
          options[:notification] = {}
          options[:notification][:title] = title
          options[:notification][:body] = body
          options[:notification][:tag] = tag
          options[:notification][:sound] = sound unless sound == 'none'
          options[:notification][:icon] = icon
          options[:notification][:color] = color
          options[:content_available] = true
          options[:data] = {}
          options[:data][:type] = data_type
          options[:data][:title] = data_title
          options[:data][:body] = data_body
          options[:data][:image_url] = data_image_url
          options[:data][:url] = data_url
    
          responses = []
          tokens.compact.each_slice(1000) do |tokens_sliced|
            response = fcm.send(tokens_sliced, options)
            responses << response
          end
          return responses.to_yaml
        end
    
      end
    end
```

Thanks!

**Comment by kashif** [comment]
@kmckinley let me ask someone at firebase to see if this is a bug on their side...

**Comment by kmckinley** [comment]
@kashif I was able to get it to work.  I had to include 'priority': 'high'.  I didn't realize this was required.  I have a question in with the Firebase team to ask them about it.

**Comment by kmckinley** [comment]
None of my tests with 'normal' priority for iOS have been delivered.  It appears for right now we need to include priority: 'high'.

**Comment by sur** [comment]
Thanks a lot everyone for great information.
I am trying to use the FCM now along with using this gem.

@kashif Thank you for quickly launching this gem!

**Comment by jegodwin** [comment]
@kmckinley I'm trying to get iOS push notifications to work as well and I'm just trying this in the console:

```
$: registration_ids = ["64_character_FB_client_token_here"]
$: options = {data: {score: "123"}, collapse_key: "updated_score"}  # just some dummy data
$: res = fcm.send(registration_ids, options)
```
...which results in this:
```
=> {:body=>"{\"multicast_id\":7789335994304170895,\"success\":0,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"error\":\"InvalidRegistration\"}]}", :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Mon, 27 Jun 2016 15:26:34 GMT"], "expires"=>["Mon, 27 Jun 2016 15:26:34 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alternate-protocol"=>["443:quic"], "alt-svc"=>["quic=\":443\"; ma=2592000; v=\"34,33,32,31,30,29,28,27,26,25\""], "accept-ranges"=>["none"], "vary"=>["Accept-Encoding"], "connection"=>["close"]}, :status_code=>200, :response=>"success", :canonical_ids=>[], :not_registered_ids=>[]}
```

Can you offer any helpful tips here? And, where are you putting the `priority: 'high'`?

Thanks in advance!

**Comment by kashif** [comment]
@jegodwin you can give the `priority: 'high'` option as one of the options in your `options = {...}`. Hope this helps!

**Comment by jegodwin** [comment]
Thanks @kashif. I did get the Push Notifications working today, but they are only coming through if the app is in the foreground. If I have the app backgrounded, then the Notification is never received. However, as soon as I open the app, the Notification comes through immediately.

If I use the Firebase Web Console to send the a Notification, then it is received when the app is in foreground OR background; so it works as expected in the Firebase Console.

Any advice on what I can try to troubleshoot this issue?

Thanks!

**Comment by jegodwin** [comment]
Disregard my last comment, I figured it out. I just needed to add the `notification` object to the payload.

**Comment by peach-adrian** [comment]
Hi, when i try to use the method sent, i obtain the next message "There was an error authenticating the sender account."

**Comment by kmckinley** [comment]
That's an expected 401 error message from Firebase, https://firebase.google.com/docs/cloud-messaging/http-server-ref#interpret-downstream

Can you send a push from the firebase console?

**Comment by ag7592** [comment]
I get this error "There was an error authenticating the sender account.", i am able to push from firebase console

**Comment by kmckinley** [comment]
Most the time I've seen this happen if the API Key isn't set properly.  Are you setting it with FCM.new(@api_key)?  Also double check for any typo's.

**Comment by sur** [comment]
I realised from Firebase docs that the "Device Group Messaging" is not yet available in FCM - it's still only available via GCM.
Calling the creation of Notification Key via fcm gem is resulting in a Google 404 response since the /fcm/notification url is not available in the API.

In that case, how can I send a message to a specific app ? considering I have multiple apps within the same project. I can not find any doc even in the Firebase docs where it mentions how to provide the App ID. Is it auto detected based on the registration tokens/ids because registration tokens are generated on per app basis ?
Could someone put some light on this please ?

Also, does anyone see the notifications sent via the gem (fcm API) will be listed in the Firebase console ?
For me they are not listed there.

Thanks very much.

**Comment by kmckinley** [comment]
I don't have the answers to your first question, but regarding the notifications being listed in the Firebase console.  No, they won't be.  Firebase Notifications(the console) is built on Firebase Cloud Messaging and isn't actually part of FCM, so it only knows of messages that are sent directly from the Firebase Notification console.

**Comment by sur** [comment]
Thanks for your inputs, Kevin.

I am doing more trials with different apps within same project and will share the outcomes as soon as I have some conclusive ones.

**Comment by waclock** [comment]
I'm having the same problem with Android. Sending messages via postman and via console works fine for me.

I've defined a simple FCM class in my server:

`class Fcm
  require 'fcm'

  def self.send_message(devices,message)
    fcm = FCM.new(ENV['FCM_KEY'])
    # you can set option parameters in here
    #  - all options are pass to HTTParty method arguments
    #  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L29-L60
    #  fcm = FCM.new("my_api_key", timeout: 3)

    registration_ids= devices # an array of one or more client registration tokens
    options = {data: {message: message},priority: 'high'}
    response = fcm.send(registration_ids, options)    
  end

end`

But I get 
{\"multicast_id\":7691638803951990239,\"success\":0,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"error\":\"InvalidRegistration\"}]}"

 as a response each time I try sending a message. I'm using the device's token and everything's working correctly using postman, using the same parameters.

Any help is appreciated.

**Comment by sur** [comment]
@waclock that's most likely the problem with registration tokens. Make sure you are getting the correct registration tokens at the client (mobile device) - it should be 152 characters long.

**Comment by waclock** [comment]
Thanks, I was having problems with the local server, tried using it on heroku and everything works fine. Maybe it has something to do with the SSL certificate.

**Comment by calvinsug** [comment]
i`m wondering what method we can use in Xcode with Objective-C code to trigger push notifications? i got the data when i send notifications from my backend server, but i`m confused to handle data from my backend server to trigger the push notifications in iOS, what method can i use? or what i`m missing?

**Comment by calvinsug** [comment]
@kmckinley have u try to use interactive notification in iOS ? have tried to add                     options[:category] = "ACTIONABLE"

but when i see the logs, the category is not appear and the notification doesn`t have interaction

**Comment by sabman** [comment]
closing as it seems resoved

**Comment by priyasaini** [comment]
Its not working for me on android. Does this gem supports only specific ruby versions. i am using 2.1.2 and here is the code:
require 'fcm'
fcm = FCM.new("FGvaSyBfI4y2yUMgv0PP")
  registration_ids = ["dicxddddLQo:APA91bH2tavLYQ5qLfEbYK-dnRvPMSGwAgPg3gWDMFA-5ZOik4S7DdSplVUP08gYt5ybrBMJU-OHtuQEUW6Ab5NN6VM7oikHNwuUPFgp-Bv4e6jv6F8aAk_4Apn9DvTvf8Ib148DOj-d"] # an array of one or more client registration tokens
         options = {}
          options[:notification] = {}
          options[:notification][:title] = "New Message"
          options[:notification][:body] = "Message goes here"
          options[:notification][:tag] = "push"
       
          options[:notification][:color] = "red"
          options[:content_available] = true
          options[:data] = {}
          options[:data][:type] = "Random"
           options[:priority] = "high"
   response = fcm.send(registration_ids, options)

**Comment by vanitu** [comment]
We are using it. 

Usually issue related not to ruby fcm gem, but application production/dev key used to get tokens. 

Easy to check if to send push messages via firebase console with token you have. 

If message not delivered via firebase console, than issue for sure not in fcm gem. 

With best regards.
Ivan Astafiev
