### ISSUE TITLE
[question] Would using Data and Notification payload send two push notification?

### ISSUE THREAD

**Issue by asyrofqomaruddin** [spacialdb/fcm#13]
Assume that I send $fcm.send(tokens, {data: some_data, notifications: some_notifications})

would that send two push notif, one contains data key and the other contains notification key?

my project seems to have this problem.

**Comment by jaz5hq** [comment]
I don't think so. I assume that  all the fcm implementation on rails are using the HTTP post method. You can have a look at the fcm http post format, they will be included in one http request

**Comment by jaz5hq** [comment]
well, it depends on your implementation for the receiving method. However, they comes in a push.

**Comment by sabman** [comment]
thanks for the answer @jaz5hq
