### ISSUE TITLE
Not working for ios 10

### ISSUE THREAD

**Issue by joney000** [spacialdb/fcm#15]
response = fcm.send(registration_ids, options) function status : "success":1, "failure":0
but did not getting on the app background.

**Comment by OrestNazarewycz** [comment]
I am noticing the same issue. Would love to hear you if you find a possible workaround

**Comment by fluxsaas** [comment]
i think yo might check this https://github.com/spacialdb/fcm/issues/1#issuecomment-223152688

passing the options:  'priority': 'high' might solve the issue.

**Comment by OrestNazarewycz** [comment]
^ that was definitely it, thanks so much for the reply 👍
