### ISSUE TITLE
Any known issues with ruby 1.9.3 ?

### ISSUE THREAD

**Issue by loicginoux** [spacialdb/fcm#19]
I would like to use this with ruby 1.9.3 but your gem does not allow it. I'll try to run it anyway but for speeding up debug time, do you know already what part of you code might have issues with that version ?

Thank you.

**Comment by sabman** [comment]
Not that I can think of. we don't use any specific 2.0 only features that were removed in 1.9.3 but just make sure all the tests pass before you start using it.
