### ISSUE TITLE
Device Group Messaging

### ISSUE THREAD

**Issue by zxr90** [spacialdb/fcm#2]
Hi, 

The correct endpoint for Device Group Messaging should be https://android.googleapis.com/gcm/notification. The current endpoint returns 404 error.

Link to FCM Docs on Device Group Messaging:
https://firebase.google.com/docs/cloud-messaging/notifications

**Comment by kashif** [comment]
thanks for the report! I will have a look shortly

**Comment by sur** [comment]
Also, I think the documentation here is incorrect:
https://github.com/spacialdb/fcm#generate-a-notification-key-for-device-group

The documentation shows to accept the parameters in a Hash form, since it didn't work, I checked the code and it accepts simply the values - as flattened params.

**Comment by kashif** [comment]
thanks @sur

**Comment by zxr90** [comment]
@kashif hope you can also add this API to recover Device Group Messaging notification key. I am currently doing it this way.

```ruby 
  def recover_notification_key(key_name, project_id)
    params = {
      query: {
        notification_key_name: key_name
      },
      headers: {
        'Content-Type' => 'application/json',
        'project_id' => project_id,
        'Authorization' => "key=#{@api_key}"
      }
    }
    response = self.class.get('https://android.googleapis.com/gcm/notification', params)
    build_response(response)
  end
```

**Comment by kashif** [comment]
@zxr90 just out of curiosity, how did you find this API?

**Comment by sur** [comment]
I think here it is: 
https://firebase.google.com/docs/cloud-messaging/notifications

This is the Notifications API on firebase docs but it still uses the "gcm" in the URLs - surely they are still just using their gcm setup with the new Firebase branding.

I think we need to keep a close watch on their API changes, looks like it's not too far that google will change the urls from gcm to fcm.

**Comment by zxr90** [comment]
@kashif found this stackoverflow answer when I was trying to recover a lost notification key.

http://stackoverflow.com/questions/26511764/user-notifications-how-to-recover-a-lost-notification-id-from-gcm
