### ISSUE TITLE
Status success, but not receiving notification.

### ISSUE THREAD

**Issue by akash-cp** [spacialdb/fcm#23]
Getting this response:

`{:body=>"{\"multicast_id\":5212874389930311708,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1490785863976498%81297788962bca0e\"}]}", :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Wed, 29 Mar 2017 11:11:03 GMT"], "expires"=>["Wed, 29 Mar 2017 11:11:03 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alt-svc"=>["quic=\":443\"; ma=2592000; v=\"37,36,35\""], "accept-ranges"=>["none"], "vary"=>["Accept-Encoding"], "connection"=>["close"]}, :status_code=>200, :response=>"success", :canonical_ids=>[], :not_registered_ids=>[]}
`

**Comment by redoc123** [comment]
Is this project still being maintained? I am facing the same issue.

response {:body=>"{\"multicast_id\":8171612389024818373,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1493924631383187%36ad764f962bca0e\"}]}", :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Thu, 04 May 2017 19:03:51 GMT"], "expires"=>["Thu, 04 May 2017 19:03:51 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alt-svc"=>["quic=\":443\"; ma=2592000; v=\"37,36,35\""], "accept-ranges"=>["none"], "vary"=>["Accept-Encoding"], "connection"=>["close"]}, :status_code=>200, :response=>"success", :canonical_ids=>[], :not_registered_ids=>[]}

I dont see notification in neither firebase nor app.

**Comment by JoeKaldas** [comment]
I am having the same problem but with iOS only

**Comment by redoc123** [comment]
Does that mean your Android notifications are working or you have nt tried android?

**Comment by JoeKaldas** [comment]
@redoc123 I have been using this library for Android since GCM turned into FCM and has been working fine. Was using another library for iOS
I integrated my iOS app fine with Firebase. And if I send a notification from Firebase console, it works perfect. But not from my server.

**Comment by redoc123** [comment]
For me its working intermittently. fcm.rb of this library contains a simple wrapper on firebase api. It just prints what Firebase gives as a response. I will have to look at why firebase is not delivering the message submitted.

**Comment by kashif** [comment]
Also can you try setting the priority of the messages to high and try?

**Comment by redoc123** [comment]
@kashif Thanks for the reply. It was my bad. In office wifi I set a proxy port for my wifi (which was down when i tested). Which was causing the issue.  

I changed my proxy settings and its working fine now.

**Comment by kashif** [comment]
@redoc123 🆒  glad it worked 👍

**Comment by JoeKaldas** [comment]
@redoc123 Are you testing on Android or iOS? If iOS, can you provide how you send your notification from the server? Also your AppDelegate class

**Comment by redoc123** [comment]
android.

**Comment by vanitu** [comment]
Solve this issue for iOS be replacing development certificate to production one in Firebase project settings for iOS app

**Comment by vaibhavxyz** [comment]
Neither setting priority worked for me nor changing to production certificate on both.

This is the JSON which I am sending

`{
    "to" : "<ID_HERE>",
    "priority" : 10,
    "mutable_content": false,
    "content_available":false,
    "data": {
      "url": "<SOM_APP_SPECIFIC_DATA>",
      "tag": "<SOME_OTHER_DATA>"
   },
    "notification" : {
      "body" : "<LOREM_IPSUM> ",
      "tag":"<LOREM IPSUM>"
    }
  }`

**Comment by gabrieldmc** [comment]
Oddly enough, i got it working in iOS with the following setup:
`
    options = {
      data: @data,
      notification: @notification,
      priority: 'high'
    }
`

But if and only if @notification contained title, body and _color_.(I swear, adding color as the last piece of code made it work)

In the end, my working version got like this:

`
@notification = {
        title: " < Same as Data title >",
        body: " < Same as Data Message >", 
        color: 'blue' #could be any other
      }
`

**Comment by vanessasoutoc** [comment]
Hi guys, notification not received in ios, my log 
`{:body=>"{\"multicast_id\":6397078158903840249,\"success\":2,\"failure\":15,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1524107216929669%6c1fb865f9fd7ecd\"},{\"error\":\"NotRegistered\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"error\":\"InvalidRegistration\"},{\"message_id\":\"0:1524107216931595%420aad7af9fd7ecd\"},{\"error\":\"NotRegistered\"},{\"error\":\"NotRegistered\"}]}", :headers=>{"content-type"=>["application/json; charset=UTF-8"], "date"=>["Thu, 19 Apr 2018 03:06:56 GMT"], "expires"=>["Thu, 19 Apr 2018 03:06:56 GMT"], "cache-control"=>["private, max-age=0"], "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "server"=>["GSE"], "alt-svc"=>["hq=\":443\"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=\":443\"; ma=2592000; v=\"43,42,41,39,35\""], "accept-ranges"=>["none"], "vary"=>["Accept-Encoding"], "connection"=>["close"]}, :status_code=>200, :response=>"success", :canonical_ids=>[], :not_registered_ids=>["d2F2AovBx8E:APA91bGdOWGvyzoiKqAf09H8V-Ar9Hzt2_bGmySLJyDCudRQ_OjKxE1rDNf5rdeK6uwT9eO-gUTffBLM-hHBvCscVO2_LIfvYdDsyXzwXc79wcbYeEobYEt4EVA5UIBSqdsiGVI6_r9p", "f65Fh8JUxIc:APA91bFnda5bcjOO5VAJuuNkWi5rBg32SWI6vN78UHDX6z8eZuBvxh-T47oxaa6v1N1qrX2TInV8FaWZf9fu-OV5vZtgSne0ftFsPs6W04DJglRomvMZ6H2FujrHt8vF-8eg9pqPrBKa", "f65Fh8JUxIc:APA91bFnda5bcjOO5VAJuuNkWi5rBg32SWI6vN78UHDX6z8eZuBvxh-T47oxaa6v1N1qrX2TInV8FaWZf9fu-OV5vZtgSne0ftFsPs6W04DJglRomvMZ6H2FujrHt8vF-8eg9pqPrBKa"]}`

in android working, in ios not received. Help me

**Comment by sabman** [comment]
seems you are not `NotRegistered` doesn't seem like a gem issue - please reopen if you think it's related to the gem
