### ISSUE TITLE
Can not send notification with Ruby 1.8.7

### ISSUE THREAD

**Issue by Jim25** [spacialdb/fcm#27]
I am using Ruby version 1.8.7.

I use this FCM gem https://github.com/spacialdb/fcm and want to send notification message to Android client app but it does not work.

In Controller:
`fcm = FCM.new(FIREBASE_API_KEY, :timeout => 30)
 options = {:data => {:message => "This is a FCM Topic Message!"}}
 response = fcm.send_to_topic('global', options)`

Class FCM:
`require 'httparty'
require 'cgi'
require 'json'
class FCM
    include HTTParty
    base_uri 'https://fcm.googleapis.com/fcm'
    default_timeout 30
    format :json

    attr_accessor :timeout, :api_key

    def initialize(api_key, client_options = {})
        @api_key = api_key
        @client_options = client_options
    end

    def send_with_notification_key(notification_key, options = {})
    body = { :to => notification_key }.merge(options)

    params = {
        :body => body.to_json,
        :headers => {
        'Authorization' => "key=#{@api_key}",
        'Content-Type' => 'application/json'
    }
  }

  response = self.class.post('/send', params.merge(@client_options))
  response.parsed_response
 end

 def send_to_topic(topic, options = {})
    if topic =~ /[a-zA-Z0-9\-_.~%]+/
    send_with_notification_key('/topics/' + topic, options)
 end
end
end`

The server key is correct, because I can send notification successfully by PHP code.
The response output as below: {"message_id"=>8885803884270587181}
Could anyone please to point out what wrong with the code. Any help would be greatly appreciated.

**Comment by willnet** [comment]
fcm looks to support >= Ruby 2.0.

https://github.com/spacialdb/fcm/blob/36f0eee2ceffe71f1667df0ba5ed76280c16d73a/fcm.gemspec#L15
