### ISSUE TITLE
SocketError (Failed to open TCP connection to fcm.googleapis.com:443)

### ISSUE THREAD

**Issue by taharushain** [spacialdb/fcm#31]
When I try to implement the example I get this error thrown at the console.

`SocketError (Failed to open TCP connection to fcm.googleapis.com:443 (getaddrinfo: Temporary failure in name resolution))`

I think it has to do that FCM API URL in the Gem is outdated. The documentation suggests the following API URL for this purpose

`https://fcm.googleapis.com/fcm/send`

**Comment by a-ta-ta** [comment]
I've faced such an issue when I had problems with my wi-fi connection.
