### ISSUE TITLE
Ios Notification is not receiving at device

### ISSUE THREAD

**Issue by pvin** [spacialdb/fcm#33]
Facing an issue with  Ios Notification which is not receiving at device. Same setup is working fine with Android. 
**Found few discussion but didn't help**
a. https://github.com/spacialdb/fcm/issues/15
b. https://github.com/spacialdb/fcm/issues/1#issuecomment-223152688

Here is my 
**Request:**

    fcm = FCM.new(ENV["FCM_TOKEN"])
    options = {data: {message: message}, priority:'high'}
    response = fcm.send(device_tokens, options)

**Response:**
{:body=>
  "{\"multicast_id\":8122297942819980145,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1505802064679190%9310a6bdf9fd7ecd\"}]}",
 :headers=>
  {"content-type"=>["application/json; charset=UTF-8"],
   "date"=>["Tue, 19 Sep 2017 06:21:04 GMT"],
   "expires"=>["Tue, 19 Sep 2017 06:21:04 GMT"],
   "cache-control"=>["private, max-age=0"],
   "x-content-type-options"=>["nosniff"],
   "x-frame-options"=>["SAMEORIGIN"],
   "x-xss-protection"=>["1; mode=block"],
   "server"=>["GSE"],
   "alt-svc"=>["quic=\":443\"; ma=2592000; v=\"39,38,37,35\""],
   "accept-ranges"=>["none"],
   "vary"=>["Accept-Encoding"],
   "connection"=>["close"]},
 :status_code=>200,
 :response=>"success",
 :canonical_ids=>[],
 :not_registered_ids=>[]}

Please let me know if i'm doing anything wrong here. 
@kmckinley  @kashif  @fluxsaas
Thank you

**Comment by Innocuousjoe** [comment]
Seeing the same problem and response - any progress here?

**Comment by Innocuousjoe** [comment]
@pvin Have you tried including a `notification` key in your data blob?  So you have something like:

    options = {}
    options[:notification] = {}
    options[:notification][:title] = "some_title"
    options[:notification][:body] = "some_body_message"
    options[:notification][:color] = 'red'
    options[:content_available] = true
    options[:data] = {}
    options[:data][:notificaiton_type] = some_type
    options[:data][:statement_id] = statement_id
    options[:data][:priority] = 'high'

That seemed to be the difference maker for me, as I just got it working!

**Comment by pvin** [comment]
No didn't tried @Innocuousjoe

**Comment by bidluo** [comment]
Have you requested the notification permission?

**Comment by sai92messy** [comment]
Initially I also faced the same issue, but then after looking for solutions, I found this comment https://github.com/spacialdb/fcm/issues/1#issuecomment-223152688.

The payload should have a notification object with title and body attrs,

`options = {
  notification: {title: "Some Title", body: "Some description"},
  data: {extra_data: {}},
  priority: 'high'
}
`
Modifying the options payload like above worked form me.

**Comment by pvin** [comment]
@sai92messy This fixed my issue.Thank you
