### ISSUE TITLE
InvalidRegistration Error with success response and status code 200

### ISSUE THREAD

**Issue by MuneebSarfraz94** [spacialdb/fcm#35]
Hi. I have just integrated fcm in my rails applications. i have tried to test the notifications but this is giving me invalid registration error although registration key is correct.
Following is the response 
`{:body=>"{\"multicast_id\":7702172266196992064,\"success\":0,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"error\":\"InvalidRegistration\"}]}",
 :headers=>
  {"content-type"=>["application/json; charset=UTF-8"],
   "date"=>["Thu, 16 Nov 2017 13:54:00 GMT"],
   "expires"=>["Thu, 16 Nov 2017 13:54:00 GMT"],
   "cache-control"=>["private, max-age=0"],
   "x-content-type-options"=>["nosniff"],
   "x-frame-options"=>["SAMEORIGIN"],
   "x-xss-protection"=>["1; mode=block"],
   "server"=>["GSE"],
   "alt-svc"=>["hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\""],
   "accept-ranges"=>["none"],
   "vary"=>["Accept-Encoding"],
   "connection"=>["close"]},
 :status_code=>200,
 :response=>"success",
 :canonical_ids=>[],
 :not_registered_ids=>[]}
`

**Comment by sabman** [comment]
@MuneebSarfraz94 are you still running into this? IF not I'll close this.

**Comment by sabman** [comment]
closing (old issue)
