### ISSUE TITLE
base uri

### ISSUE THREAD

**Issue by raniaakh** [spacialdb/fcm#39]
Hi anyone, why base uri declare like:
`base_uri 'https://fcm.googleapis.com/fcm'`

not:
`base_uri 'https://fcm.googleapis.com/fcm/send'`

I cant work properly. Please tell me

**Comment by sabman** [comment]
because of this https://github.com/spacialdb/fcm/blame/b76473b005a0b03860d5ae5f7c0c67f854359adf/lib/fcm.rb#L44
