### ISSUE TITLE
Handle more registration ids

### ISSUE THREAD

**Issue by letiesperon** [spacialdb/fcm#40]
Hi! 

It would be cool it the gem took care of splitting more than 1000 registration tokens into batches.

**Comment by sabman** [comment]
@letiesperon thanks for using the gem. 

The max limit from Firebase is currently 1000 - this could for example change... and we wanna keep this gem very lean minimizing complexity and all the good things that entails from that.  Also I don't like the idea of side effects - so each send call should do just that make one send call.

maybe using the [each_slice](https://ruby-doc.org/core-2.2.0/Enumerable.html#method-i-each_slice)
`token_ids.each_slice(1000) { |ids| send(ids, message)  }`

**Comment by sabman** [comment]
@letiesperon thanks for using the gem.

The max limit from Firebase is currently 1000 - this could for example change... and we wanna keep this gem very lean minimizing complexity and all the good things that entails from that. Also I don't like the idea of side effects - so each send call should do just that - make one send call.

maybe just stick with each_slice
`token_ids.each_slice(1000) { |ids| send(ids, message) }`
