### ISSUE TITLE
You can still send to invalid topics (regex)

### ISSUE THREAD

**Issue by quilligana** [spacialdb/fcm#41]
This code tries to stop you from sending to topics that don't match the valid regex provided on FCM.
```
def send_to_topic(topic, options = {})
  if topic =~ /[a-zA-Z0-9\-_.~%]+/
    send_with_notification_key('/topics/' + topic, options)
  end
end
```

But the `=~` method will still match a string that has invalid characters in it, as long as there are valid characters in it. [see here].(https://ruby-doc.org/core-2.2.0/Regexp.html#method-i-3D~)

So the following can happen:
```
$ topic = "TopicA$"
$ topic =~ /[a-zA-Z0-9\-_.~%]+/
$ => 0
```

Can we change this to return false when invalid characters are present in the topic? Something like this maybe?
```
$ topic = "TopicA$"
$ topic.gsub(/[a-zA-Z0-9\-_.~%]+/, "").length == 0
$ => false
```

**Comment by sabman** [comment]
closed in #42
