### ISSUE TITLE
FCM response 

### ISSUE THREAD

**Issue by ArunanRamanathan** [spacialdb/fcm#43]
Firebase Response={\"multicast_id\":6346611008984444477,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1527570229728811%746f20adf9fd7ecd\"}]}
But My firebase console didnt receive any message May i know the correction 

Thanks in Advance

**Comment by sabman** [comment]
Out of date. Please try with the new version. closing for now.
