### ISSUE TITLE
Response says "success" but the client never receives any push.

### ISSUE THREAD

**Issue by stabenfeldt** [spacialdb/fcm#44]
I'm able to send push notifications to $RECIPIENT when I'm using console.firebase.com.
If I send with [spacialdb/fcm][1], then no push is sent. Even though the reply from the server looks ok. => *(:status_code=>200, :response=>"success")*

Any idea what might be wrong? 

**code**

```ruby
    require 'fcm'
    
    fcm = FCM.new('$TOKEN')
    
    
      # An array of one or more client registration tokens
    registration_ids = ['$RECIPIENT']
    
    options = { data: { score: '123' }, collapse_key: 'updated_score' }
    response = fcm.send(registration_ids, options)
    puts "Sendt: #{response}"


```
  [1]: https://github.com/spacialdb/fcm

**running code**

```ruby
    $ ruby fcm.rb
    
    Sendt: {:body=>"{\"multicast_id\":60356242858746826,\"success\":1,\"failure\":0,
    \"canonical_ids\":0,
        \"results\":[{\"message_id\":\"0:1528896392320437%e06a962bca0e\"}]}", 
    :headers=>{"content-type"=>["application/json; charset=UTF-8"],
        "date"=>["Wed, 13 Jun 2018 13:26:32 GMT"], "expires"=>["Wed, 13 Jun 2018 13:26:32 GMT"], "cache-control"=>["private, max-age=0"],
        "x-content-type-options"=>["nosniff"], "x-frame-options"=>["SAMEORIGIN"], 
    "x-xss-protection"=>["1; mode=block"],
        "server"=>["GSE"], "alt-svc"=>["quic=\":443\"; ma=2592000; v=\"43,42,41,39,35\""],
        "accept-ranges"=>["none"], "vary"=>["Accept-Encoding"],
         "connection"=>["close"]}, :status_code=>200, :response=>"success",
        :canonical_ids=>[], :not_registered_ids=>[]}
```

**Comment by vanitu** [comment]
Check that you use production key. 

With best regards.
Ivan Astafiev

**Comment by stabenfeldt** [comment]
I'm using the same TOKEN listed as Web API key I found under settings.
That's the production key you're referring to, right? I get a "not authorized" error if I change that.
<img width="1330" alt="screenshot 2018-06-14 10 17 50" src="https://user-images.githubusercontent.com/181272/41400085-688e794c-6fbc-11e8-94a7-0a0b6c6c3096.png">

**Comment by stabenfeldt** [comment]
The error was that I was sending a data push notification. My app was not ready to accept that.
When I changed the options to ` { "notification": { "title": "Portugal vs. Denmark", "text": "5 to 1" }}` then I received the message.

I've created a PR #45 that hopefully will make it easier for the next newbie that comes along. :-)
