### ISSUE TITLE
Error while trying to use fcm

### ISSUE THREAD

**Issue by leonmuchoki** [spacialdb/fcm#5]
Am getting this error: LoadError (cannot load such file -- fcm), while trying to use fcm gem. But if i use gcm it has no error. But i upgraded to using firebase.
I have it in my gemfile and i have tried out everything i can. Can any one help me out please?

This is my class that i use to send the notification with

```ruby
class Device < ActiveRecord::Base

	require 'fcm'

  def self.notify_android(recipient)
    	fcm = FCM.new(".....")
		registration_ids= recipient # an array of one or more client registration tokens
		options = {data: {hi: "invoice"}}
		response = fcm.send(registration_ids, options)
  end

end
```

**Comment by sur** [comment]
Simple steps to diagnose:

* have you done "bundle install" after mentioning it in Gemfile ?
* when you do "gem list fcm" on terminal does it show fcm gem installed ?
* can you try requiring fcm in IRB - does it work there ?

**Comment by leonmuchoki** [comment]
I have done all that, it even shows in the gem list. My ruby version is 2.1.5 (in windows) and i have tried it locally and also using heroku where i have hosted my app.
It still says 500 internal server error and then LoadError

**Comment by selivandex** [comment]
I have the sampe bug
