### ISSUE TITLE
Should we use Faraday instead of HTTParty to support MultiThreading?

### ISSUE THREAD

**Issue by prcongithub** [spacialdb/fcm#51]
HTTParty uses class variables which are modified by this gem everytime we make HTTP request.

This is obviously not threadsafe.

We could use [Faraday](https://github.com/lostisland/faraday) instead which uses instance variables to create  HTTP connections and supports JRuby as well.

I have made [these changes](https://github.com/prcongithub/fcm/commit/0c6f9488ca13ac67c0c19e2de7f907b06bbaa6ce) and it seems to be working pretty well so far.

Any comments?

**Comment by sabman** [comment]
would love to but seems your branch is off an old fork. Can you make sure you fork it off the master of spacialdb/fcm Right now I can't merge it:
https://github.com/spacialdb/fcm/compare/master...prcongithub:faraday

**Comment by prcongithub** [comment]
We had added some more functionality in our fork for this.

I have sent a PR for the same here now: https://github.com/spacialdb/fcm/pull/52/files

I will send another PR to use Faraday once the above gets merged.

**Comment by prcongithub** [comment]
Here is a PR to replace HTTParty with Faraday.
It has been working well for us since last month with our JRuby API. We are using 10 sidekiq threads to send push notifications without any issues!
https://github.com/spacialdb/fcm/pull/55

**Comment by buncismamen** [comment]
since it's merged could we close this issue then?

**Comment by sabman** [comment]
new release pushed https://github.com/spacialdb/fcm/releases/tag/0.0.7
