### ISSUE TITLE
GCM api usage in GROUP_NOTIFICATION_BASE_URI

### ISSUE THREAD

**Issue by igorigorigorigor** [spacialdb/fcm#56]
Since GCM will be deprecated in April, Is it okey to use gcm for this constant? 
`GROUP_NOTIFICATION_BASE_URI = 'https://android.googleapis.com/gcm'`

**Comment by igorigorigorigor** [comment]
https://firebase.google.com/docs/cloud-messaging/android/device-group

**Comment by sabman** [comment]
Out of date. Please try with the new version. closing for now.
