### ISSUE TITLE
Initializer FCM through an initializer

### ISSUE THREAD

**Issue by rands0n** [spacialdb/fcm#62]
Hi, I was recently using your gem to send messages to Firebase. But I don't like to configure an instance always when I want to send.

So about that, I was thinking about creating an initializer way to configure the gem before sending notifications. Instead of doing this:

```ruby
require 'fcm'

fcm = FCM.new('API_KEY')

registration_ids = ['11', '12']
options = {
  title: 'Portugal vs Denmark',
  body: '5x1'
}

fcm.send(registration_ids, options)
```

And start doing this:

```ruby
# config/initializers/fcm.rb
require 'fcm'

FCM.configure do |config|
  config.api_key = 'MY_API_KEY'
end
```

And the file I want to send notifications, just:

```ruby
FCM.send(registration_ids, options)
```

I was working this morning on a version of that, but I stopped to try to view if this is useful right now. What do you think about that?

**Comment by tianqiwuben** [comment]
For this use case, I would usually create a global variable in any initializer.

**Comment by rands0n** [comment]
@tianqiwuben How?

**Comment by diogoleitao** [comment]
@rands0n just create a `firebase.rb` initializer with something like `FIREBASE = FCM.new(ENV['FIREBASE_SERVER_KEY'])` and use `FIREBASE.send` wherever you want
