### ISSUE TITLE
Support to click action

### ISSUE THREAD

**Issue by thefuga** [spacialdb/fcm#63]
When sending the field `click_action` to a Flutter app, nothing happens (the field is not received in the push notification).
This is the body I'm sending:

```
{
     notification: {
         title: 'Title',
         body: 'Message',
         tag: 'Update',
         click_action: 'FLUTTER_NOTIFICATION_CLICK'
 }
```

Doesn't this gem support this or am I doing something wrong?

**Comment by nuzelac** [comment]
Hi @thefuga,

I'm working on the same thing right now, but I didn't test push notifications yet. From what the `flutter_messaging` README says, the `click_action` should go to the `data` section:

```json
{
   "notification":{
      "body":"this is a body",
      "title":"this is a title"
   },
   "priority":"high",
   "data":{
      "click_action":"FLUTTER_NOTIFICATION_CLICK",
      "id":"1",
      "status":"done"
   },
}
```

**Comment by sabman** [comment]
Can you please try with the latest release?
https://rubygems.org/gems/fcm/versions/1.0.1

**Comment by thefuga** [comment]
I'm not working on the project which used this, but I'll let them know. Thank you!
