### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by dankimio** [spacialdb/fcm#65]

**Comment by bryanp** [comment]
We're needing this as well. The current version depends on an old version of `httparty` that conflicts with other gems in our project. Right now we're pointed at `master`, which is not ideal.

What's the ETA on a new release?

**Comment by ashkulz** [comment]
Any update, @sabman / @kashif?

**Comment by sabman** [comment]
Sorry for the delay. we'll try to get to it this week. Just need to ensure test coverage. If you think any tests are missing please let me know. Otherwise we can push a release by the end of the week.

**Comment by dankimio** [comment]
Any updates?

**Comment by sabman** [comment]
✅ release pushed 🎉 
Thanks for all the work and promoting me 
<img width="550" alt="root_0bcbbab83596____cartodb_and_GitHub_Desktop" src="https://user-images.githubusercontent.com/1907/75607025-315db900-5af3-11ea-83b6-6ed8458282a6.png">
