### ISSUE TITLE
Faraday version

### ISSUE THREAD

**Issue by marcoschicote** [spacialdb/fcm#71]
Hi
Is there a reason why you are using `faraday` version `0.15.4` specifically (https://github.com/spacialdb/fcm/blob/master/fcm.gemspec#L22) ?

At this point `faraday` is on version `1.0.0`. Would it be possible to be less strict on faraday version?

Thanks
Marcos

**Comment by kochka** [comment]
Was about to ask the same question :)

**Comment by buncismamen** [comment]
yeah I want to use faraday version `1.0.0`

**Comment by sabman** [comment]
new release pushed https://github.com/spacialdb/fcm/releases/tag/v1.0.0
Thank you for your help: @bidluo @olleolleolle and everyone else!

**Comment by marcoschicote** [comment]
thanks!
