### ISSUE TITLE
Keyword arguments not supported 

### ISSUE THREAD

**Issue by tarr11** [spacialdb/fcm#8]
All of the examples use the keyword argument format 

fcm.add(notification_key: "foo", project_id: "123" ..)

But these are not actually supported by the library, which requires parameters by position.

**Comment by kashif** [comment]
thanks @tarr11 will have a look!

**Comment by patricks** [comment]
The `notification_key` is deprecated:

https://firebase.google.com/docs/cloud-messaging/http-server-ref
